# Generated by Django 5.1.6 on 2025-02-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
